language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.5
env:
  - DB=sqlite3
  #- DB=mysql
  #- DB=postgresql
script:
  #- RAILS_ENV=test bundle exec rake db:migrate --trace
  #- bundle exec rake db:test:prepare
  - bundle exec rake spec
#before_script:
  #- cp config/database.travis.yml config/database.yml
  #- mysql -e 'create database strano_test'
  #- psql -c 'create database strano_test' -U postgres

